[project]
name = "mcp-server"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "fastmcp==2.4.0",
    "lxml>=5.4.0",
    "mcp>=1.9.1",
    "nest-asyncio>=1.6.0",
    "openai>=1.82.0",
    "playwright>=1.52.0",
]

